[build]
# Railpack automatically detects Bun and SQLite
builder = "RAILPACK"

[deploy]
# Production-ready configuration
startCommand = "bun start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 10

# Persistent storage for SQLite databases and attachments
volumes = [
  { source = "/app/data", target = "/app/data" },
  { source = "/app/storage", target = "/app/storage" }
]

# Port configuration
[deploy.env]
PORT = "3000"

# Production environment with optimized settings
[environments.production.variables]
NODE_ENV = "production"
# Performance optimization
REFRESH_INTERVAL = "86400"  # 24 hours
CACHE_TTL = "86400"        # 24 hours
# Storage paths with persistent volumes
SQLITE_PATH = "/app/data"
STORAGE_PATH = "/app/storage/attachments"
ENABLE_ATTACHMENT_DOWNLOAD = "true"
# Security (set in Railway UI)
# AIRTABLE_PERSONAL_TOKEN = "${AIRTABLE_PERSONAL_TOKEN}"
# AIRTABLE_BASE_ID = "${AIRTABLE_BASE_ID}"
# BEARER_TOKEN = "${BEARER_TOKEN}"

# Staging environment for testing
[environments.staging.variables]
NODE_ENV = "staging"
# Faster refresh for testing
REFRESH_INTERVAL = "3600"   # 1 hour
CACHE_TTL = "3600"         # 1 hour
# Isolated storage paths
SQLITE_PATH = "/app/data/staging"
STORAGE_PATH = "/app/storage/staging"
ENABLE_ATTACHMENT_DOWNLOAD = "true"
# Security (set in Railway UI)
# AIRTABLE_PERSONAL_TOKEN = "${AIRTABLE_PERSONAL_TOKEN}"
# AIRTABLE_BASE_ID = "${AIRTABLE_BASE_ID}"
# BEARER_TOKEN = "${BEARER_TOKEN}"
